### ISSUE TITLE
Plugin fails for links without quotes

### ISSUE THREAD

**Issue by Gerrit-K** [zinit-zsh/z-a-as-monitor#1]
I was just trying to configure zinit to pull the latest pulumi binary when I encountered some errors. Debugging the plugin revealed that it expects links in the form of `<a href="..." />` (i.e. quoted), but unfortunately the pulumi download page only lists them without quotes.

I know it's not common to have unquoted html attributes and I could also file an issue at pulumi/docs, but I was able to fix it quite easily:

```diff
diff --git "a/\342\206\222za-as-monitor-preinit-handler" "b/\342\206\222za-as-monitor-preinit-handler"
index 3a52243..de83eb6 100755
--- "a/\342\206\222za-as-monitor-preinit-handler"
+++ "b/\342\206\222za-as-monitor-preinit-handler"
@@ -91,9 +91,11 @@ for cur_paturl ( $pattern_url0 $pattern_url ) {
     }

     local -a list
-    list=( ${(@f)"$(noglob command egrep -io "href=.$cur_paturl" $tmpfile)"} )
+    list=( ${(@f)"$(noglob command egrep -io "href=.?$cur_paturl" $tmpfile)"} )

-    local selected=${list[1]#href=?}
+    local selected=${list[1]#href=}
+    selected=${selected#\"}
+    selected=${selected#\'}

     if [[ -z $selected ]] {
         builtin print -P -- "${ZINIT[col-pre]}as-monitor annex: ${ZINIT[col-error]}ERROR:%f" \
```

Of course, the expansions to remove the possible quotes look ugly, but I'm sure you could find a more elegant solution 😉 

What do you think? Is it worth implementing and could you see any risk?

**Comment by psprint** [comment]
I don't see any risks so I've commited the solution. I've only changed the two last lines of the diff to:

```zsh
    selected=${selected#[\"\']}
````

Thanks!

**Comment by Gerrit-K** [comment]
Thanks for the quick fix! I just tested it and I can confirm it works. Closing the issue.
