### ISSUE TITLE
Usage with web-server autoindex

### ISSUE THREAD

**Issue by mcanevet** [zinit-zsh/z-a-as-monitor#3]
Is it possible to use this extension to download a program when there is no web-page that hosts the URL to the file to download, but only an autoindex page generated by the web server?
For example : https://mirror.openshift.com/pub/openshift-v4/clients/ocp/
I tried with this:
```
zinit id-as"oc" as="monitor|command" extract \
  dlink"/pub/openshift-v4/clients/ocp/%VERSION%/openshift-client-linux-%VERSION%.tar.gz" \
  for https://mirror.openshift.com/pub/openshift-v4/clients/ocp/
```
But I get
```
as-monitor annex: ERROR: couldn't match the URL at the download page (which is https://mirror.openshift.com/pub/openshift-v4/clients/ocp; the snippet is being identified as oc; was matching /pub/openshift-v4/clients/ocp/[.,a-zA-Z0-9_-]+/openshift-client-linux-[.,a-zA-Z0-9_-]+.tar.gz).
```

**Comment by psprint** [comment]
I've updated the annex to meet the requirements of the package. Check out the [annex web page](https://github.com/zinit-zsh/z-a-as-monitor/#filtering-the-matched-urls) for an example Zinit invocation.

**Comment by mcanevet** [comment]
It works like a charm. Thanks a lot.
